[tool.poetry]
name = "spotify-to-plex"
version = "0.1.0"
description = ""
authors = ["cmathews393 <chloe@catastrophesoftware.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
plexapi = "^4.15.5"
python-decouple = "^3.8"
requests = "^2.31.0"
spotipy = "^2.23.0"
urllib3 = "^2.0.7"
schedule = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
