name: Create Issue from TODO

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Ensure at least the last two commits are available for diff generation

      - name: Run TODO to Issue Action
        uses: alstr/todo-to-issue-action@v5.1.3

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_ISSUES: false
